name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      # Step 3: Install backend dependencies (root)
      - name: Install backend dependencies
        run: npm install
        working-directory: .

      # # Step 4: Install frontend dependencies (commented out)
      # - name: Install frontend dependencies
      #   run: npm install --force
      #   working-directory: ./frontend

      # # Step 5: Build the frontend application (commented out)
      # - name: Build frontend application
      #   run: npm run build
      #   working-directory: ./frontend

      # Step 6: Setup SSH for Deployment
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H dev.zealits.com >> ~/.ssh/known_hosts

      # Step 7: Deploy to the server using git fetch/reset and npm ci for speed
      - name: Deploy to server
        if: github.ref == 'refs/heads/main'
        run: |
          ssh admin@dev.zealits.com << 'EOF'
            # Backup config.env if it exists
            if [ -f ~/BiddingApp/config/config.env ]; then
              cp ~/BiddingApp/config/config.env ~/config.env.bak
            fi

            # If repository exists, fetch changes and reset; otherwise, clone it
            if [ -d ~/BiddingApp ]; then
              cd ~/BiddingApp
              git fetch origin
              git reset --hard origin/main
            else
              git clone https://github.com/zealits/BiddingApp.git ~/BiddingApp
              cd ~/BiddingApp
            fi

            # Restore config.env if backup exists
            if [ -f ~/config.env.bak ]; then
              mv ~/config.env.bak ~/BiddingApp/config/config.env
            fi

            # Install backend dependencies using npm ci (faster clean install)
            npm ci

            # Install frontend dependencies and build
            cd frontend
            npm ci --force
            npm run build
            cd ..

            # Reload the application using PM2 for minimal downtime
            if pm2 list | grep -q "BiddingApp"; then
              echo "Reloading BiddingApp"
              pm2 reload BiddingApp || pm2 restart BiddingApp
            else
              echo "Starting BiddingApp"
              pm2 start npm --name "BiddingApp" -- run dev
            fi

            # Display PM2 process list for verification
            pm2 list
          EOF
